[package]
name = "linestring-simplify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo24 = { package = "geo", version = "0.24.0" }
geo23 = { package = "geo", version = "0.23.1" }
